#pragma once

const char* index_page_html = "<!DOCTYPE html>"
"<html>"
"    <head>"
"        <title>ESP32 POW</title>"
"        <style>"
"            body {"
"                background-color: rgb(225, 238, 207);"
"            }"
""
"            .button_container {"
"                display: flex;"
"                align-items: center;"
"                justify-content: center;"
"            }"
""
"            .button {"
"                width: 100px;"
"                height: 100px;"
"                font-size: larger;"
"            }"
"        </style>"
"    </head>"
"    <body>"
"        <div class='button_container'>"
"            <button class='button' onclick='window.location.href=\"/pow_on\"'>Start PC</button>"
"        </div>"
"        "
"    </body>"
"</html>";

const char* gpio_page_html = "<!DOCTYPE html>"
"<html>"
"    <body>"
"        <script>"
"            window.location.href = '/';" // Change to your target URL
"        </script>        "
"    </body>"
"</html>";